enum AssetId {
	Asset_stencilFS = 1,
	Asset_forwardVS,
	Asset_forwardFS,
	Asset_basicVS,
	Asset_basicFS,

	Asset_consoleFont,
	Asset_entityFont,

	Asset_menuMusic,
	Asset_levelMusic_0,
	Asset_levelMusic_1,
	Asset_levelMusic_2,

	Asset_attribute,
	Asset_behaviour,
	Asset_changerReadout,
	Asset_consoleButtonDefault,
	Asset_consoleButtonClicked,
	Asset_consoleButtonUnavailable,

	Asset_marineCityBg,
	Asset_marineCityMg,
	Asset_sunsetCityBg,
	Asset_sunsetCityMg,
	
	Asset_dockAcceptButtonDefault,
	Asset_dockAcceptButtonClicked,
	Asset_dockAcceptButtonHover,
	Asset_dockCancelButtonDefault,
	Asset_dockCancelButtonClicked,
	Asset_dockCancelButtonHover,
	Asset_barEnergy,
	Asset_energyBarStencil,
	Asset_dock,
	Asset_subDock,
	Asset_gravityField,
	Asset_timeField,

	Asset_mainMenuBg,
	Asset_mainMenuAnim,
	Asset_mainMenuOptionsButton,
	Asset_mainMenuPlayButton,
	Asset_mainMenuQuitButton,

	Asset_motherShipBase,
	Asset_motherShipEmitter,
	Asset_motherShipProjectile,
	Asset_motherShipProjectileDeath,
	Asset_motherShipProjectileSmoking,
	Asset_motherShipRotator1,
	Asset_motherShipRotator2,
	Asset_motherShipRotator3,
	Asset_motherShipShoot,

	Asset_pauseMenuBg,
	Asset_pauseMenuAnim,
	Asset_pauseMenuQuitButton,
	Asset_pauseMenuRestartButton,
	Asset_pauseMenuResumeButton,
	Asset_pauseMenuSettingsButton,

	Asset_playerDeath,
	Asset_playerHacking,
	Asset_playerJumpingIntro,
	Asset_playerJumping,
	Asset_playerJumpingOutro,
	Asset_playerRunning,
	Asset_playerStand,

	Asset_shrikeBootUp,
	Asset_shrikeStand,
	Asset_shrikeShoot,

	Asset_cornerTileHackShield,
	Asset_tileHackShield,
	Asset_tileHackButton,

	Asset_corner1Regular,
	Asset_corner1Glowing,
	Asset_disappearRegular,
	Asset_disappearGlowing,
	Asset_heavyRegular,
	Asset_heavyGlowing,
	Asset_middle1Regular,
	Asset_middle1Glowing,
	Asset_top1Regular,
	Asset_top1Glowing,
	Asset_top2Regular,
	Asset_top2Glowing,

	Asset_trawlerBody,
	Asset_trawlerBolt,
	Asset_trawlerBoltDeath,
	Asset_trawlerBootUp,
	Asset_trawlerRightFrame,
	Asset_trawlerShoot,
	Asset_trawlerWheel,

	Asset_trojanBolt,
	Asset_trojanBoltDeath,
	Asset_trojanDisappear,
	Asset_trojanFull,
	Asset_trojanShoot,

	Asset_virus3BaseOff,
	Asset_virus3BaseOn,
	Asset_virus3LaserBeam,
	Asset_virus3TopOff,
	Asset_virus3TopOn,

	Asset_currentWaypoint,
	Asset_currentWaypointLine,
	Asset_defaultWaypoint,
	Asset_defaultWaypointLine,
	Asset_movedWaypoint,
	Asset_movedWaypointLine,
	Asset_selectedWaypoint,
	Asset_waypointArrow,

	Asset_circle,
	Asset_triangle,
	Asset_white,

	Asset_cursorDefault,
	Asset_cursorHacking,

	Asset_endPortal,
	Asset_energy,
	Asset_light0,
	Asset_light1,

	Asset_checkPointReached,
	Asset_checkPointUnreached,

	Asset_count
};
